name: Create a dummy PR

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Remove this workflow file now that it has done its job
        run: git rm .github/workflows/create-dummy-pr.yml

      - name: Use CLA approved bot
        run: .github/scripts/use-cla-approved-bot.sh

      - name: Create pull request against the release branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          message="A dummy PR to give otelbot-java-contrib one merged PR under its belt"
          branch="otelbot/dummy-pr"

          git checkout -b $branch
          git commit -a -m "$message"
          git push --set-upstream origin $branch
          gh pr create --title "$message" \
                       --body "$message." \
                       --base main
